Buyme-App/Buyme-app-PF

- client/src/components/Account/Account.jsx
Arreglado y era algo bien simple
> FIX: Arreglado el problema de que no se actualizaba la lista de users

- client/src/App.js
- client/src/components/User/Login/LoginUser.jsx
- client/src/components/User/Login/LoginUser.module.css
- client/src/components/User/Login/PasswordRecovery/PasswordRecovery.jsx
- client/src/components/User/Login/PasswordRecovery/PasswordRecovery.module.css
- client/src/components/User/Login/SignUp/SignUp.jsx
- client/src/components/User/Login/SignUp/SignUp.module.css
acá te agrego los componentes del loginUser, sign up y recuperar contraseña. Le agregue algún control de errores.
> Login client

- client/src/components/AdminNewProduct/AdminNewProduct.jsx
- client/src/components/User/Featured/Featured.jsx
- client/src/components/User/Featured/Featured.module.css
- client/src/components/User/ProductDetail/ProductDetail.jsx
- client/src/components/User/ProductDetail/ProductDetail.module.css
Just a PR to save my work and be able to Pull all the repo
> Product Detail & Featured

- client/src/components/Account/Account.jsx
- client/src/components/Account/Account.module.css
Lucas ya agregue lo que me pediste de la tabla de usuarios, thread, tbody, etc
> Account dashboard

- api/index.js
- client/src/App.js
- client/src/components/User/Featured/Featured.jsx
- client/src/components/User/ProductDetail/ProductDetail.jsx
- client/src/redux/actions/index.js
- client/src/redux/reducer/index.js
> Redux Update

- client/src/redux/actions/index.js
> Added missing sendKey()

- client/src/components/Account/Account.jsx
- client/src/redux/actions/index.js
- client/src/redux/reducer/index.js
acá esta la funcionalidad para eliminar usuarios
> delete users in component account

- client/src/components/AdminNewProduct/AdminNewProduct.jsx
- client/src/components/User/Cards/Cards.jsx
- client/src/components/User/Featured/Featured.jsx
- client/src/components/User/ProductDetail/ProductDetail.jsx
- client/src/components/User/ProductDetail/ProductDetail.module.css
Improved rendering of product default image when missing images
> Fixes render when missing img

- api/src/token/auth.token.js
- client/src/components/AdminNewProduct/AdminNewProduct.jsx
- client/src/components/AdminNewProduct/AdminNewProduct.module.css
- client/src/components/Login/controllers/tokenFunctions.js
- client/src/redux/actions/index.js
> Fix new product

- client/src/components/AdminHome/AdminHome.jsx
- client/src/components/AdminNewProduct/AdminNewProduct.jsx
- client/src/components/AdminProducts/AdminProducts.jsx
Corregidos algunos bugs nimios
> Fixing new product

- client/src/components/Account/Account.jsx
- client/src/components/Account/AddUsers/AddUser.jsx
- client/src/components/Account/ChangeEmail/ChangeEmail.jsx
Solucioné el loop de Account, igualmente hay que seguir testeando. Ese componente no está completo en funcionalidades como les compañeres habian asentado
> fixed (Account) : loop of the useEffect

- client/src/components/AdminProducts/AdminProducts.jsx
> fixed (newProduct): yes and no

- client/src/App.js
- client/src/components/User/Header/Header.jsx
- client/src/components/User/Login/LoginUser.jsx
lucas agregué funcionalidad para ir desde el botón my account del home al login del cliente y en el login al hacer submit va a la landing nuevamente. Tambien cambie el nombre de la ruta a "/login" como me pediste.
> route from myAccount to loginClient, login to home

- .vscode/launch.json
- client/src/components/UpdateProduct/UpdateProduct.jsx
- client/src/components/UpdateProduct/updateProduct.module.css
Quite el checkbox de offerPrice en Update
> Fixing update

- client/src/components/AdminProducts/AdminProducts.jsx
- client/src/components/AdminProducts/AdminProducts.module.css
- client/src/components/Sales/Sales.jsx
- client/src/components/Sales/sales.module.css
Solucionado el cartel notMatch cuando haces búsquedas en el serchbar
> fixed (Product searchbar): not match found fixed

- client/src/components/User/Cards/Cards.jsx
- client/src/components/User/Cards/Cards.module.css
- client/src/components/User/Cards2/Cards2.jsx
- client/src/components/User/Featured/Featured.jsx
- client/src/components/User/ProductDetail/ProductDetail.jsx
- client/src/components/User/ProductDetail/ProductDetail.module.css
Some minor adjustments for price display
> Price adjustments cards & detail

- client/src/components/Account/Account.jsx
- client/src/components/Account/AddUsers/AddUser.jsx
- client/src/components/Account/ChangeEmail/ChangeEmail.jsx
- client/src/components/basics/myInput.jsx
- client/src/redux/actions/index.js
- client/src/redux/reducer/index.js
Funciona el cambio de correo pero no se cierra el form cuando se hace submit
> Account comp

- client/src/components/User/Login/LoginUser.jsx
- client/src/components/User/Login/LoginUser.module.css
- client/src/components/User/Login/SignUp/SignUp.jsx
- client/src/components/User/Login/SignUp/SignUp.module.css
ya agregue el botón para loguearse con google (sin funcionalidad)
> btn login with google added

- client/src/components/User/Cards/Cards.jsx
- client/src/components/User/Landing/Landing.jsx
- client/src/redux/actions/index.js
- client/src/redux/reducer/index.js
Solo agregué un action que trae los productos al cliente, cada vez que se monta el componente Landing.  Aún hay que ver la parte de details que faltan algunos componentes
> Added (action): getProductsclient

- client/src/App.js
- client/src/components/User/Featured/Featured.jsx
- client/src/components/User/ProductDetail/ProductDetail.jsx
- client/src/components/User/Search/Search.jsx
- client/src/components/User/Search/Search.module.css
- client/src/components/User/Search/SideBar.jsx
- client/src/components/User/Search/SideBar.module.css
- client/src/components/User/SearchBar/SearchBar.jsx
- client/src/redux/actions/index.js
- client/src/redux/reducer/index.js
Updated actions and reducers and related components
> Updated routes for Clients

- client/src/components/User/Search/Search.jsx
Fixes so every seach ends up in this page
> Search results page

- client/src/App.js
- client/src/components/User/Careers/Careers.jsx
- client/src/components/User/Careers/Careers.module.css
- client/src/components/User/Footer/Footer.jsx
- client/src/components/User/Footer/Footer.module.css
- client/src/components/User/ProductDetail/ProductDetail.jsx
- client/src/components/User/ProductDetail/ProductDetail.module.css
- client/src/components/User/Sustainability/Sustainability.jsx
- client/src/components/User/Sustainability/Sustainability.module.css
- client/src/components/User/Terms/Terms.jsx
- client/src/components/User/Terms/Terms.module.css
Just added some dummy pages (Terms & Conditions, etc)
> Context pages and navigation

- client/src/components/User/ProductDetail/ProductDetail.jsx
- client/src/components/User/ProductDetail/ProductDetail.module.css
Use Inventory as threshold to trigger stock alert individually per product
> Product Detail Stock Alert

- client/src/components/User/Cart/Cart.jsx
- client/src/components/User/Cart/Item/Item.jsx
- client/src/components/User/Cart/cart.module.css
- client/src/redux/actions/index.js
- client/src/redux/reducer/index.js
funcionalidades principales del carrito
> cart features

- client/src/components/User/NavBar/Dropdown.jsx
- client/src/components/User/NavBar/Dropdown.module.css
- client/src/components/User/NavBar/NavBar.jsx
- client/src/components/User/NavBar/NavBar.module.css
Categories Dropdown Menu. Links still to be defined.
> Categories Dropdown Menu

- client/src/components/User/Search/Search.jsx
- client/src/components/User/Search/Search.module.css
- client/src/redux/actions/index.js
- client/src/redux/reducer/index.js
Filtros por destacado, con descuento y ordenamiento por precio
> Filters & Order

- api/src/controllers/cart/getCart.controller.js
- api/src/controllers/cart/logCart.controller.js
- api/src/controllers/cart/updateCart.controller.js
- api/src/controllers/mercadopago/createInvoiceMP.controller.js
- api/src/controllers/mercadopago/notificationOrder.controller.js
- api/src/database/db.js
- api/src/models/Cart.model.js
- api/src/routes/cart/getCart.routes.js
- api/src/routes/cart/logCart.routes.js
- api/src/routes/cart/updateCart.routes.js
- api/src/routes/mercadopago/mpAccess.route.js
- api/src/routes/mercadopago/notificationOrder.route.js
archivos de pasarela y modelo de carrito y funciones modificar, recuperar y mezclar al logeo preferencias con carrito en db.
db.js agrega las relaciones de  Cart, se debe agregar a index.routes lo siguiente
//cart
const logCart = require('./cart/logCart.routes');
const getCart = require('./cart/getCart.routes');
const updateCart=require('./cart/updateCart.routes');
//cart
server.use('/getCart', getCart);
server.use('/updateCart', updateCart);
server.use('/logCart', logCart);
> jose pasarela y algo del carrito

- client/src/App.js
- client/src/components/User/Login/LoginUser.jsx
- client/src/components/User/MyAccount/Dropdown.jsx
- client/src/components/User/MyAccount/Dropdown.module.css
- client/src/components/User/MyProfile/MyProfile.jsx
- client/src/components/User/MyProfile/MyProfile.module.css
- client/src/redux/actions/index.js
- client/src/redux/reducer/index.js
hola ale, aca puse todos mis cambios, espero que esten bien
> My profile

- client/src/components/User/Landing/Landing.jsx
- client/src/components/User/Slider/Sliderex/FP.jsx
- client/src/components/User/Slider/Sliderex/FP.module.css
Componente FP LISTO y renderizado en la landing page
> FP-FINISHED

- client/src/components/User/Cart/Cart.jsx
Resolví los conflictos del carrito
> cartsolved

- api/index.js
- api/src/controllers/category/getCatById.controller.js
- api/src/routes/category/getCatById.routes.js
- api/src/routes/index.routes.js
> agregada ruta para devolver todos los productos de una sola categoria

- api/src/controllers/product/getAllProducts.controller.js
- client/src/components/User/ProductDetail/ProductDetail.jsx
- client/src/components/User/Search/Search.jsx
- client/src/redux/actions/index.js
- client/src/redux/reducer/index.js
• Updated Get All Product Controller to include Categories & Subcategories Models
• Categories Filter (WIP, not working yet)
• Display Category name in Product Detail
> Categories filter (WIP) and Updated New Prod Controller

- client/src/components/User/Cart/Cart.jsx
- client/src/redux/actions/index.js
Se preparó la variable que se va a enviar a mercado pago, falta solamente el clientId. También en el actions ya se preparó la ruta de mercado pago
> cart-backend1

- api/src/controllers/product/updateProduct.controller.js
- api/src/routes/product/updateProduct.routes.js
- client/src/components/UpdateProduct/UpdateProduct.jsx
Render current Categories, Subcategories and Status in Update Product form. Sill working in updating them in the DB.
> WIP Product Update Status, Cats & Subcats

- api/src/routes/mail/sendMail.routes.js
agrego una priemra version de la ruta para mandar email, funciona pero no tiene modelo ni controlador, la logica esta toda aca
> (add-route):ruta para enviar email

- client/src/App.js
- client/src/components/AdminHome/AdminHome.jsx
- client/src/components/User/CheckoutPages/Page1(Cart)/CartConfirmed.jsx
- client/src/components/User/CheckoutPages/Page2Form/ClientForm.jsx
- client/src/components/User/CheckoutPages/Page3Success/SuccessBA.jsx
- client/src/components/User/CheckoutPages/Page3Success/SuccessBA.module.css
- client/src/redux/actions/index.js
- client/src/redux/reducer/index.js
> cartfinished1

- client/src/components/User/CheckoutPages/Page1(Cart)/CartConfirmed.jsx
- client/src/components/User/CheckoutPages/Page2Form/ClientForm.jsx
- client/src/components/User/CheckoutPages/Page3Success/SuccessBA.jsx
- client/src/redux/actions/index.js
- client/src/redux/reducer/index.js
> agus-cart-w

- client/src/components/User/CheckoutPages/Page1(Cart)/CartConfirmed.jsx
> cartsolved4

- client/src/components/User/MyOrders/MyOrders.jsx
- client/src/components/User/MyOrders/MyOrders.module.css
- client/src/redux/actions/index.js
- client/src/redux/reducer/index.js
agregue la funcionalidad a my orders, ya se ven las ordenes realizadas, si no hay ninguna muestra mensaje
> added getInvoiceByClient

- client/src/components/User/MyAccount/Dropdown.jsx
> logoutcart

- api/src/controllers/transport/transport.controller.js
- api/src/routes/transport/transport.route.js
Ahi va lo de email transporte\
hay que agregar a routes 
const transport = require('./transport/transport.route');
server.use('/transport', transport);  //para cargar la orden de transporte y disparar el email de despachado;
y al .env  con un www.ethereal creado en el momento en local
ETHEREAL_USER=jarvis.moen39@ethereal.email
ETHEREAL_PASSWORD=Ry8BpggVjR6ZEBXPTU
ETHEREAL_HOST=smtp.ethereal.email
> jueves-camion

- client/src/components/User/CheckoutPages/Page3Success/SuccessBA.jsx
- client/src/redux/actions/index.js
> cartsolveddelete
